---
- hosts: all
  vars:
    - home: /home/myuser
    - java_version: 21

  pre_tasks:
    - name: Installing SDKMAn dependencies
      apt:
        state: latest
        name:
          - zip
          - unzip

  tasks:
    - name: Installing SDK Man
      become: no
      shell: "curl -s 'https://get.sdkman.io' | bash"
      args:
          executable: /bin/bash

    - name: Adding SDK Man to bash_profile
      lineinfile: path={{ home }}/.bash_profile
        line={{ item }}
        state=present
        create=yes
      with_items:
        - 'source "$HOME/.sdkman/bin/sdkman-init.sh"'

    - name: Installing Java
      shell: source ~/.bash_profile && sdk install java {{ java_version }}
      become: no
      args:
        executable: /bin/bash