---
roles:
  # - name: gantsign.sdkman
  #   src: git@github.com:gantsign/ansible_role_sdkman.git
  #   version: master
  #   scm: git
  - name: comcast.sdkman
    src: git@github.com:Comcast/ansible-sdkman.git
    version: master
    scm: git