---
roles:
  - name: comcast.sdkman
    src: git@github.com:Comcast/ansible-sdkman.git
    version: master
    scm: git
  - name: ansible-role-golang
    src: git@github.com:gantsign/ansible-role-golang.git
    version: master
    scm: git